site_url: https://peterchen.xyz
site_name: Tech Notes
site_description: Keep track of all the learning
site_author: Pete

# Repository
repo_name: 'advpetc/Tech_Notes'
repo_url: 'https://github.com/advpetc/tech_notes/'

theme:
  font:
    text: Ubuntu Mono
  name: material
  include_search_page: false
  search_index_only: true
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
  feature:
    tabs: true
  custom_dir: overrides
  palette: 
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
  - scheme: slate 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

extra:
  pagetime: 'on'
  manifest: 'assets/images/site.webmanifest'
  disqus: 'tech-notes-2'
  analytics:
      provider: google
      property: UA-168812075-1
extra_css:
  - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized:
      exclude:
        - index.md
