name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip     # install pip
          python3 -m pip install -r requirements.txt      # install via requirements.txt
      - name: Build site
        run: mkdocs build
      - name: Desploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: $
          publish_dir: ./site